name: Build Module

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v3
      with:
        path: main-repo

    - name: Checkout dependency repository at specific commit
      uses: actions/checkout@v3
      with:
        repository: benaclejames/VRCFaceTracking
        ref: 04717cc936d5307796064aafa3dd2a862dfdd02e # VRCFT build 5.1.1.0
        path: VRCFaceTracking

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # VRCFT builds on .NET 7

    - name: Restore dependencies
      run: dotnet restore main-repo/VRCFT-QuestProOpenXR.sln

    - name: Build
      run: dotnet build --configuration Release main-repo/VRCFT-QuestProOpenXR.sln
